In [2]:
import pandas as pd
import numpy as np
import os
import urllib
import zipfile

## Download Data

In [3]:
if not os.path.isfile('./sudoku.csv'):
    opener = urllib.URLopener()
    opener.retrieve('https://www.kaggle.com/bryanpark/sudoku/downloads/sudoku.zip', 'data.zip')
    zip_ref = zipfile.ZipFile('./data.zip', 'r')
    zip_ref.extractall('./')
    zip_ref.close()
    os.remove('./data.zip')
    print('Data downloaded and unzipped')
else:
    print('Data exist')

Data exist


## Load Data and Check

In [2]:
table = pd.read_csv('./sudoku.csv')
table.head()

quizzes  \
0  0043002090050090010700600430060020871900074000...   
1  0401000501070039605200080000000000170009068008...   
2  6001203840084590720000060050002640300700800069...   
3  4972000001004000050000160986203000403009000000...   
4  0059103080094030600275001000300002010008200070...   

                                           solutions  
0  8643712593258497619712658434361925871986574322...  
1  3461792581875239645296483719658324174729168358...  
2  6951273841384596727248369158512647392739815469...  
3  4972583161864397252537164986293815473759641828...  
4  4659123781894735623275681497386452919548216372...

In [3]:
data = table.as_matrix()
data[0,0]

'004300209005009001070060043006002087190007400050083000600000105003508690042910300'

In [6]:
exp1 = [int(x) for x in data[0,0]]
np.array(exp1).reshape(9,9)

array([[0, 0, 4, 3, 0, 0, 2, 0, 9],
       [0, 0, 5, 0, 0, 9, 0, 0, 1],
       [0, 7, 0, 0, 6, 0, 0, 4, 3],
       [0, 0, 6, 0, 0, 2, 0, 8, 7],
       [1, 9, 0, 0, 0, 7, 4, 0, 0],
       [0, 5, 0, 0, 8, 3, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 1, 0, 5],
       [0, 0, 3, 5, 0, 8, 6, 9, 0],
       [0, 4, 2, 9, 1, 0, 3, 0, 0]])

## Transfer Data into Numpy Array

In [15]:
quizzes = np.zeros((1000000, 81), np.int32)
solutions = np.zeros((1000000, 81), np.int32)
for i, line in enumerate(open('sudoku.csv', 'r').read().splitlines()[1:]):
    quiz, solution = line.split(",")
    for j, q_s in enumerate(zip(quiz, solution)):
        q, s = q_s
        quizzes[i, j] = q
        solutions[i, j] = s
quizzes = quizzes.reshape((-1, 9, 9))
solutions = solutions.reshape((-1, 9, 9))

In [16]:
quizzes.shape

(1000000, 9, 9)

In [18]:
transfer_data = np.concatenate((quizzes.reshape(-1, 1, 81), solutions.reshape(-1, 1, 81)), axis=1)

In [19]:
transfer_data.shape

(1000000, 2, 81)

In [20]:
transfer_data[0,0,:]

array([0, 0, 4, 3, 0, 0, 2, 0, 9, 0, 0, 5, 0, 0, 9, 0, 0, 1, 0, 7, 0, 0, 6,
       0, 0, 4, 3, 0, 0, 6, 0, 0, 2, 0, 8, 7, 1, 9, 0, 0, 0, 7, 4, 0, 0, 0,
       5, 0, 0, 8, 3, 0, 0, 0, 6, 0, 0, 0, 0, 0, 1, 0, 5, 0, 0, 3, 5, 0, 8,
       6, 9, 0, 0, 4, 2, 9, 1, 0, 3, 0, 0], dtype=int32)

In [21]:
transfer_data[0,1,:]

array([8, 6, 4, 3, 7, 1, 2, 5, 9, 3, 2, 5, 8, 4, 9, 7, 6, 1, 9, 7, 1, 2, 6,
       5, 8, 4, 3, 4, 3, 6, 1, 9, 2, 5, 8, 7, 1, 9, 8, 6, 5, 7, 4, 3, 2, 2,
       5, 7, 4, 8, 3, 9, 1, 6, 6, 8, 9, 7, 3, 4, 1, 2, 5, 7, 1, 3, 5, 2, 8,
       6, 9, 4, 5, 4, 2, 9, 1, 6, 3, 7, 8], dtype=int32)

In [23]:
np.save('tranfer_data', transfer_data)